fixtures:
  repositories:
    'stdlib':
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.0.0'
    'openssl': 'https://github.com/camptocamp/puppet-openssl.git'
  symlinks:
    nssdb: "#{source_dir}"
